name: 'Release-aware web Docker image create & push'

on:
  workflow_dispatch:
  push:
    branches: [ master, helm-charts ]
    paths:
    - 'client/*'
    - '.github/workflows/web-docker-image.yml'
  pull_request:
    branches: [ master ]
    paths:
    - 'client/*'
    - '.github/workflows/web-docker-image.yml'
jobs:

  build-and-push-web-image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd ./client
        docker build . --file Dockerfile --tag sdpequinor/release-aware-web:latest
        echo ${{ secrets.DOCKERHUB_PAT }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push sdpequinor/release-aware-web:latest
        docker logout
